### ISSUE TITLE
No release generated

### ISSUE THREAD

**Issue by wencywww** [progit/progit2-bg#4]
@jnavila 
Just checking if there is any problems, because i committed a week ago with still no new release?

**Comment by jnavila** [comment]
Please revert .travis.yml to its original content.

**Comment by jnavila** [comment]
I just don't get what happened. If I have a look at the last generated tag, the content of the `.travis.yml` file is [correct](https://github.com/progit/progit2-bg/blob/2.1.43/.travis.yml), but I cannot find back in the history of the present file the correct content at some point back in time.

How could this happen? Did you force-push the whole history?

**Comment by wencywww** [comment]
Hardly.
To be honest i even don't know how to accomplish this (to force-push the history). 
Moreover, this file does not need any translation work so i never touch it locally.

**Comment by jnavila** [comment]
Should be back to normal.
