### ISSUE TITLE
The book is not compiled

### ISSUE THREAD

**Issue by jnavila** [progit/progit2-bg#43]
### There's no existing/similar bug report.

- [X] I have searched the existing issues

### This report is about a single actionable bug.

- [X] I'm reporting a single actionable bug

### This report is about the ProGit book, version 2, English language.

- [ ] This bug is not about a translation or old version

### Bug covers book website/pdf

- [X] I confirm the bug is about the book as found on the website/pdf

### Problem is present in the Pro Git book on the website?

- [X] This bug also affects the Pro Git book as published on the website.

### Which version of the book is affected?

Tooling

### Describe the bug:

You copied the recipe for github actions from progit, but they do not apply to your repo. The recipes expect the trunk branch's name to be "main", but yours is still "master". As a consequence, the build is not triggered.

### Steps to reproduce:

1. commit a change
2. go to page ["Actions"](https://github.com/progit/progit2-bg/actions/workflows/release-on-merge.yml)
3. There's no build triggered

### Expected behavior:

Each new push should build the pdf, epub, html and mobi files.

**Comment by wencywww** [comment]
The '**main**' branch has been created and pushed, the release is done. Pls, delete the '**master**' branch as i have no permissions to do that.

**Comment by jnavila** [comment]
Done. Thanks!
